# inside.ini
# Semi-universal configuration file
# Suitable for rootless and roothide environment
# Created by AD on 17/1/26
# Copyright (c) 2026 AD All rights reserved

# 內部命名
export EXPERIMENTAL="$Experimental"
export LOG_REINCARNATION="$Log_Reincarnation"
export LOOP_MODE="$loop"
export OPTIMIZE_INTERVAL="$Optimize_Interval"
export DEBUG_MODE="$Debug_Mode"
export DYNAMIC_OPTIMIZATION="$Dynamic_Optimization"
export AUTO_OPTIMIZER="$Auto_Optimizer"
export USE_SUDO="$use_sudo"
# 內部參數
export High_Priority="$High_Priority"
export Low_Priority="$Low_Priority"
export Dynamic_Priority="$Dynamic_Priority"
export Launchd_Priority="$Launchd_Priority"
export Loop_Sleep_Interval="$Loop_Sleep_Interval"

export HIGH_PRIORITY="$High_Priority"
export LOW_PRIORITY="$Low_Priority"
export JETSAM_PRIORITY="$Dynamic_Priority"
export LAUNCHD_PRIORITY="$Launchd_Priority"
export LOOP_SLEEP_INTERVAL="$Loop_Sleep_Interval"
export AUTO_ADJUST="$Auto_Adjust"
export MODULE_SWITCH="$a1_module_switch"
export CUSTOM_PRIORITY_ENABLED="$Custom_Priority_Enabled"

# 国际语言内部变量定义名
export LOCALE_A1="$locale_a1"
export LOCALE_A1CTL="$locale_a1ctl"
export LOCALE_A1MOD="$locale_a1mod"
export LOCALE_A1_ALL="$locale_a1_all"