#!/bin/bash
#build.sh
set -ex
script_path="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

source ${script_path}/ci/env.sh
source ${script_path}/ci/package.sh
source ${script_path}/ci/build-tool.sh
source ${script_path}/ci/generate-version.sh

b_a1() {
    local lua_patch_file="${script_path}/paths/loslib_lsystem.patch"
    if [ "$use_lua_cache" = false ]; then
        cd ${script_path}/libs/lua
        cp loslib.c loslib.c.orig
        patch -p0 < ${lua_patch_file}
        make clean
        make CC="$(command -v clang) -target arm64-apple-ios14.0" a
        rm -f loslib.c && mv loslib.c.orig loslib.c
        cd ${script_path}
        clang++ -ObjC++ \
         $CXXFLAGS \
         ${src_path}/src/cxxa1.cc -o cxxa1 \
         -lm ${script_path}/libs/lua/liblua.a
    else
        if [ ! -f "${script_path}/libs/lua/liblua.a" ]; then
            echo "[Error]: cache: ${script_path}/libs/lua/liblua.a does not exist" && exit 1;
        else
            clang++ -ObjC++ \
             $CXXFLAGS \
             ${src_path}/src/cxxa1.cc -o cxxa1 \
             -lm ${script_path}/libs/lua/liblua.a
        fi
    fi
    sign bin cxxa1
}

b_a1ctl() {
    clang++ -ObjC++ \
     $CXXFLAGS \
     -lzip \
     ${src_path}/src/cxxa1ctl.cc -o cxxa1ctl
    sign bin cxxa1ctl
}

b_a1mod() {
    clang++ -ObjC++ \
     $CXXFLAGS \
     -lzip -lssl -lcrypto \
     ${src_path}/src/cxxa1mod.cc -o cxxa1mod
    sign bin cxxa1mod
}

b_a1pm() {
    clang++ -ObjC++ \
     $CXXFLAGS \
     -lzip -lcurl -lssl -lcrypto \
     ${src_path}/src/cxxa1pm.cc -o cxxa1pm
    sign bin cxxa1pm
}

b_gui() {
    src_gui=${script_path}/src/gui
    local CXXFLAGS="$CXXFLAGS -I${src_gui} -framework UIKit -framework CoreGraphics -framework QuartzCore"
    clang++ -ObjC++ -fobjc-arc \
        $CXXFLAGS \
        -Wno-deprecated-declarations \
        -DA1_USE_GUI_CFG \
        -lzip -lcurl -lssl -lcrypto \
        ${src_gui}/app/*.mm \
        ${src_gui}/ui/Categories/*.mm \
        ${src_gui}/ui/ViewControllers/*.mm \
        ${src_gui}/core/*.mm \
        -o a1gui
    sign gui a1gui
}

show_help() { echo "usage: $0 [a1|a1ctl|a1mod|a1pm|a1gui] [build-a1-all|build-a1-tool|build-a1] [pack-a1|pack-a1gui|pack-all] [--a1-use-lua-cache]" >&2; }

if [ $# -eq 0 ]; then
    show_help
    exit 1;
fi

use_lua_cache=false
for arg in "$@"
do
    if [ $arg = "--a1-use-lua-cache" ]; then
        use_lua_cache=true
        break
    fi
done

for target in "$@"
do
    case $target in
        a1)
            generate_version a1
            b_a1
            ;;
        a1ctl)
            generate_version a1ctl
            b_a1ctl
            ;;
        a1mod)
            generate_version a1mod
            b_a1mod
            ;;
        a1pm)
            generate_version a1pm
            b_a1pm
            ;;
        a1gui)
            generate_version gui
            b_gui
            ;;
        build-a1-all|build-a1)
            generate_version all
            b_a1
            b_a1ctl
            b_a1mod
            b_a1pm
            b_gui
            ;;
        --package-a1|pack-a1) pack_a1 ;;
        --package-a1gui|pack-a1gui) pack_a1gui ;;
        --package-all|pack-all) pack_all ;;
        build-a1-tool) build_tool ;;
        --a1-use-lua-cache) break ;;
        *)
            echo "unknown target: $target" >&2
            show_help
            exit 1;
            ;;
    esac
done
