#!/bin/bash -ex

source ".git-upload/instructions.ini"
export text="$instructions"

git submodule update --remote libs/libxmz
git submodule update --remote libs/lua

git add .
git diff --staged --quiet || git commit -m "updated by the update script; $text; $(date +'%Y-%m-%d %H:%M')"

git pull --rebase
git push origin main
git push codeberg main
