#version.ini
[old_version]
a1_version = 1.9.9-beta3-2+debug14
gui_version = 0.0.3-beta3-2

[new_version]
a1_version = 2.0.0.129
a1ctl_version = 2.0.0.65
a1mod_version = 2.0.0.59
a1pm_version = 2.0.0.54

