#version.ini
[old_version]
a1_version = 1.9.9-beta3-2+debug14
gui_version = 0.0.3-beta3-2

[new_version]
a1_version = 2.0.0.211
a1ctl_version = 2.0.0.123
a1mod_version = 2.0.0.123
a1pm_version = 2.0.0.112
gui_version = 0.1.3.34
general_version = 2.0.1.0