# config.conf
# 通用配置

export Experimental=false
export Log_Reincarnation=false
export loop=false
export Optimize_Interval=1800
export Debug_Mode=true
export use_sudo_all=true
export use_sudo_a1=true
export use_sudo_a1ctl=true
export Loop_Sleep_Interval=5
export use_root_a1ctl=true
export Auto_Apply=false
export Auto_Adjust=false
export SCHEDULED_GUARD=false
export a1_module_switch=false
export Custom_Priority_Enabled=false
export compat_mode=false

# 优先级配置
export High_Priority=0
export Low_Priority=39
export Launchd_Priority=20
export Dynamic_Priority=15

# lock
export lock_use=true

# 国际化支持
export locale_a1=true
export locale_a1ctl=true
export locale_a1mod=true
export locale_a1module="$locale_a1mod"
export locale_a1_all=true