#!/bin/bash

if [ -f '/etc/profile' ]; then
    source /etc/profile
elif [ -f '/var/jb/etc/profile' ]; then
    source /var/jb/etc/profile
else
    echo 'Where the fuck "profile"?' 1>&2
fi

if [ "$(dpkg --print-architecture)" = "iphoneos-arm64" ]; then
    jb="/var/jb"
else
    jb=""
fi

jb_a1="$jb/a1"

_finish(){
	f="${1}"
	[ -z "${f}" ] || [ -z "${SILEO}" ] && return
	read -r fd ver <<-EOF                    
			${SILEO}                                    
			EOF
	[ "${ver}" -ge 1 ] || return
	echo "finish:${f}" >&"${fd}"
}

echo "Tweak by LF"
echo "正在为你干活！"
echo "---------------------------------"
echo "|Maintainer: LF, AD|Project: A1 |"
echo "---------------------------------"

echo "setting..."
chmod 755 $jb/usr/local/bin/a1*
chown 0:0 $jb/usr/local/bin/a1*

ln -sf $jb/usr/local/bin/a1 $jb/usr/local/bin/al
ln -sf $jb/usr/local/bin/a1ctl $jb/usr/local/bin/alctl
ln -sf $jb/usr/local/bin/a1mod $jb/usr/local/bin/almod
ln -sf $jb/usr/local/bin/a1module $jb/usr/local/bin/almodule
ln -sf $jb/usr/local/bin/a1hub $jb/usr/local/bin/alhub

chmod 644 "$jb/Library/LaunchDaemons/a1.launch.plist"

chmod u+s $jb/usr/local/bin/a1hub
chmod u+s $jb/opt/a1/bin/raise_power

mkdir -p $jb/bin
ln -sf /bin/ps $jb/bin/
(
    if [ "$(dpkg --print-architecture)" = "iphoneos-arm64" ]; then
        jb="/var/jb"
    else
        jb=""
    fi

    jb_a1="$jb/a1"

    cd "$jb_a1"
    ln -sf autofonf.ini autoconf.ini
)

# the newly added compatibility mode should not need this

echo "A1 install done."
echo "Enjoy！"

_finish usreboot