#!/bin/bash

if [ -f '/etc/profile' ]; then
    source /etc/profile
elif [ -f '/var/jb/etc/profile' ]; then
    source /var/jb/etc/profile
else
    echo 'Where the fuck "profile"?' 1>&2
fi

if [ "$(dpkg --print-architecture)" = "iphoneos-arm64" ]; then
    jb="/var/jb"
else
    if [ "$(dpkg --print-architecture)" = "iphoneos-arm64e" ]; then
        unset jb;
        jb="$(jbroot)"
    else
        unset jb;
        jb=""
    fi
fi

jb_a1="$jb/a1"

_finish(){
	f="${1}"
	[ -z "${f}" ] || [ -z "${SILEO}" ] && return
	read -r fd ver <<-EOF                    
			${SILEO}                                    
			EOF
	[ "${ver}" -ge 1 ] || return
	echo "finish:${f}" >&"${fd}"
}

echo "Tweak by LF"
echo "Sto lavorando per te!"
echo "----------------------------"
echo "|Author: LF                |"
echo "| Maintainer: LF, AD, XMZ  |"
echo "|Project: A1               |"
echo "----------------------------"

echo "setting..."
chown 0:0 $jb/usr/local/bin/a1cil
chown 0:0 $jb_a1/bin/*
chmod 4755 $jb_a1/bin/*

if [ "$(dpkg --print-architecture)" = "iphoneos-arm64e" ]; then
    orig_path=$(pwd)
    [ -d "/rootfs" ] && cd /rootfs/var
    [ ! -d "jb" ] && ln -s / ./jb
    ls -l /rootfs/var/jb
    cd $orig_path
    unset orig_path
fi

echo "A1 install done."
echo "Enjoy！"

_finish usreboot
