### example config ###
[YouURL]
;;url: https://example.com/yourepo
;;last_sync: UpdateTime
######################

[https://xmz-team.github.io/a1repo]
url: https://xmz-team.github.io/a1repo
last_sync: 
