# config.ini

Experimental = false
Log_Reincarnation = false
loop = false
Optimize_Interval = 1800
Debug_Mode = true
Loop_Sleep_Interval = 5
Auto_Apply = false
Auto_Adjust = false
SCHEDULED_GUARD = false
a1_module_switch = false
Custom_Priority_Enabled = false
compat_mode = false

# 优先级配置
High_Priority = 0
Low_Priority = 39
Launchd_Priority = 20
Dynamic_Priority = 15

# lock
lock_use = true

# sudo and root
use_sudo_all = true
use_sudo_a1 = true
use_sudo_a1ctl = true
use_root_a1ctl = true