    export HIGH_PRIORITY="${HIGH_PRIORITY:-0}"
    export LOW_PRIORITY="${LOW_PRIORITY:-39}"
    export LAUNCHD_PRIORITY="${LAUNCHD_PRIORITY:-20}"
    export JETSAM_PRIORITY="${JETSAM_PRIORITY:-15}"
    export MAX_CPU_PERCENT="${MAX_CPU_PERCENT:-15}"
    # mode on/off
    export LOOP_MODE="${LOOP_MODE:-false}"
    export AUTO_ADJUST="${AUTO_ADJUST:-false}"
    export SCHEDULED_GUARD="${SCHEDULED_GUARD:-false}"
    export EXPERIMENTAL="${EXPERIMENTAL:-false}"
    export LOG_REINCARNATION="${LOG_REINCARNATION:-false}"
    export CUSTOM_PRIORITY_ENABLED="${CUSTOM_PRIORITY_ENABLED:-false}"
    export DEBUG_MODE="${DEBUG_MODE:-true}"
    # gap set
    export OPTIMIZE_INTERVAL="${OPTIMIZE_INTERVAL:-1800}"
    export LOOP_SLEEP_INTERVAL="${LOOP_SLEEP_INTERVAL:-5}"
    # Permission set
    export USE_SUDO_ALL="${USE_SUDO_ALL:-true}"
    export USE_SUDO_A1="${USE_SUDO_A1:-true}"
    export USE_SUDO_A1CTL="${USE_SUDO_A1CTL:-true}"
    export USE_ROOT_A1CTL="${USE_ROOT_A1CTL:-true}"
    # other
    export COMPAT_MODE="${COMPAT_MODE:-false}"
    export LOCK_USE="${LOCK_USE:-true}"
    export DYNAMIC_OPTIMIZATION="${DYNAMIC_OPTIMIZATION:-false}"
