name: Build and package cxxa1

on:
  workflow_dispatch:
  push:

jobs:
  build:
#    runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      run: |
        git -c url."https://github.com/".insteadOf="git@github.com:" submodule update --init --recursive
        chmod +x build
        chmod +x ci/*.sh
        mkdir -p tmp/bin && cd tmp/bin
        wget "https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_arm64"
        ln -sf ldid_macosx_arm64 ldid
        cd ../..
        chmod +x tmp/bin/*
        brew install dpkg
        mkdir -p tmp/lib
        #libzip5
        wget "https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1800/libzip/libzip5_1.9.2_iphoneos-arm64.deb"
        wget "https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1800/libzip/libzip-dev_1.9.2_iphoneos-arm64.deb"
        dpkg-deb -R libzip-dev_1.9.2_iphoneos-arm64.deb libzip-dev
        dpkg-deb -R libzip5_1.9.2_iphoneos-arm64.deb libzip5
        #libcurl
        wegt "https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1800/curl/libcurl4_8.7.1_iphoneos-arm64.deb"
        wegt "https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1800/curl/libcurl4-openssl-dev_8.7.1_iphoneos-arm64.deb"
        dpkg-deb -R libcurl4_8.7.1_iphoneos-arm64.deb lincurl
        dpkg-deb -R libcurl4-openssl-dev_8.7.1_iphoneos-arm64.deb libcurl-openssl-dev
        #openssl
        wget "https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1800/openssl/libssl3_3.2.1_iphoneos-arm64.deb"
        wegt "https://apt.procurs.us/pool/main/iphoneos-arm64-rootless/1800/openssl/libssl-dev_3.2.1_iphoneos-arm64.deb"
        dpkg-deb -R libssl3_3.2.1_iphoneos-arm64.deb libssl3
        dpkg-deb -R libssl-dev_3.2.1_iphoneos-arm64.deb libssl-dev
        cd ../..

    - name: Build
      run: |
        ./build build-a1-all build-a1-tool

    - name: Package
      run: |
        ./build pack-all

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: cxxa1-packages
        path: packages/packdeb/
