name: Build and package cxxa1

on:
  workflow_dispatch:
  push:

jobs:
  build:
#    runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      run: |
        git -c url."https://github.com/".insteadOf="git@github.com:" submodule update --init --recursive
        chmod +x build
        chmod +x ci/*.sh
        mkdir -p tmp/bin && cd tmp/bin
        wget "https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_arm64"
        ln -sf ldid_macosx_arm64 ldid
        cd ../..
        chmod +x tmp/bin/*
        brew install dpkg

    - name: Build
      run: |
        ./build build-a1-all build-a1-tool

    - name: Package
      run: |
        ./build pack-all

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: cxxa1-packages
        path: packages/packdeb/
